# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VSApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'SkyFloatingLabelTextField', '~> 3.0'

  # Pods for VSApp

  target 'VSAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'VSAppUITests' do
    # Pods for testing
  end

end
